/*
 * Welcome to use the TableGo Tools.
 *
 * http://www.tablego.cn
 *
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 *
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
package com.vp.bookstore.pojo;

import lombok.Data;


public class Afteruser implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5996558110637492928L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** arid */
    private Integer arid;

    /** arname */
    private String arname;

    /** arpassword */
    private String arpassword;

    /** bumen */
    private String bumen;

    /** quanxian */
    private String quanxian;

    /** danwei */
    private String danwei;

    /** address */
    private String address;

    /** phone */
    private String phone;

    /** email */
    private String email;

    /** qq */
    private String qq;



    public Integer getArid() {
        return arid;
    }

    public void setArid(Integer arid) {
        this.arid = arid;
    }

    public String getArname() {
        return arname;
    }

    public void setArname(String arname) {
        this.arname = arname;
    }

    public String getArpassword() {
        return arpassword;
    }

    public void setArpassword(String arpassword) {
        this.arpassword = arpassword;
    }

    public String getBumen() {
        return bumen;
    }

    public void setBumen(String bumen) {
        this.bumen = bumen;
    }

    public String getQuanxian() {
        return quanxian;
    }

    public void setQuanxian(String quanxian) {
        this.quanxian = quanxian;
    }

    public String getDanwei() {
        return danwei;
    }

    public void setDanwei(String danwei) {
        this.danwei = danwei;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getQq() {
        return qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }
}