package com.vp.bootstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:24
 * @Version: 1.0
 */

import lombok.Data;

import java.sql.Timestamp;

/**
 * 书籍信息表
 */
@Data
public class BookInfo implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = -8977923589642342968L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 书籍ID */
    private Integer book_id;

    /** 书籍名称 */
    private String book_name;

    /** 书的价格 */
    private Double book_price;

    /** 折扣等级 */
    private Double book_discount;

    /** 书折扣价 */
    private Double book_discountprice;

    /** 书的图片 */
    private String book_img;

    /** 书的详情 */
    private String book_details;

    /** 书的状态1代表通过 */
    private Integer book_status;

    /** 书的类型 */
    private Integer book_typeid;

    /** 适合班级 */
    private Integer book_fitclass;

    /** 书的作者 */
    private String book_auth;

    /** 上传用户 */
    private Integer userid;

    /** 是否可以兑换 */
    private Integer book_isexchange;

    /** 出版社 */
    private String book_press;

    /** 时间 */
    private Timestamp book_date;

    /** 收藏数量 */
    private Integer book_collection;

    /** 售出数量 */
    private Integer book_sell;

    /** 库存 */
    private Integer book_stock;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getBook_id() {
        return book_id;
    }

    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    public String getBook_name() {
        return book_name;
    }

    public void setBook_name(String book_name) {
        this.book_name = book_name;
    }

    public Double getBook_price() {
        return book_price;
    }

    public void setBook_price(Double book_price) {
        this.book_price = book_price;
    }

    public Double getBook_discount() {
        return book_discount;
    }

    public void setBook_discount(Double book_discount) {
        this.book_discount = book_discount;
    }

    public Double getBook_discountprice() {
        return book_discountprice;
    }

    public void setBook_discountprice(Double book_discountprice) {
        this.book_discountprice = book_discountprice;
    }

    public String getBook_img() {
        return book_img;
    }

    public void setBook_img(String book_img) {
        this.book_img = book_img;
    }

    public String getBook_details() {
        return book_details;
    }

    public void setBook_details(String book_details) {
        this.book_details = book_details;
    }

    public Integer getBook_status() {
        return book_status;
    }

    public void setBook_status(Integer book_status) {
        this.book_status = book_status;
    }

    public Integer getBook_typeid() {
        return book_typeid;
    }

    public void setBook_typeid(Integer book_typeid) {
        this.book_typeid = book_typeid;
    }

    public Integer getBook_fitclass() {
        return book_fitclass;
    }

    public void setBook_fitclass(Integer book_fitclass) {
        this.book_fitclass = book_fitclass;
    }

    public String getBook_auth() {
        return book_auth;
    }

    public void setBook_auth(String book_auth) {
        this.book_auth = book_auth;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getBook_isexchange() {
        return book_isexchange;
    }

    public void setBook_isexchange(Integer book_isexchange) {
        this.book_isexchange = book_isexchange;
    }

    public String getBook_press() {
        return book_press;
    }

    public void setBook_press(String book_press) {
        this.book_press = book_press;
    }

    public Timestamp getBook_date() {
        return book_date;
    }

    public void setBook_date(Timestamp book_date) {
        this.book_date = book_date;
    }

    public Integer getBook_collection() {
        return book_collection;
    }

    public void setBook_collection(Integer book_collection) {
        this.book_collection = book_collection;
    }

    public Integer getBook_sell() {
        return book_sell;
    }

    public void setBook_sell(Integer book_sell) {
        this.book_sell = book_sell;
    }

    public Integer getBook_stock() {
        return book_stock;
    }

    public void setBook_stock(Integer book_stock) {
        this.book_stock = book_stock;
    }
}
