package com.vp.bootstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:35
 * @Version: 1.0
 */

import lombok.Data;

import java.util.List;

/**
 * 书类别表
 */
@Data
public class BookType implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = -6518188627038432257L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** booktypeId */
    private Integer booktype_id;

    /** booktypeName */
    private String booktype_name;
    private String booktype_detailname;
    private List<String> erji;

    public List<String> getErji() {
        return erji;
    }

    public void setErji(List<String> erji) {
        this.erji = erji;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getBooktype_id() {
        return booktype_id;
    }

    public void setBooktype_id(Integer booktype_id) {
        this.booktype_id = booktype_id;
    }

    public String getBooktype_name() {
        return booktype_name;
    }

    public void setBooktype_name(String booktype_name) {
        this.booktype_name = booktype_name;
    }

    public String getBooktype_detailname() {
        return booktype_detailname;
    }

    public void setBooktype_detailname(String booktype_detailname) {
        this.booktype_detailname = booktype_detailname;
    }
}
