package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:39
 * @Version: 1.0
 */

import lombok.Data;

import java.sql.Timestamp;

/**
 * 评论表
 */

public class Comment implements java.io.Serializable{
    private static final long serialVersionUID = 5659758877323700536L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 评论表ID */
    private Integer comment_id;

    /** bookId */
    private Integer book_id;

    /** userId */
    private Integer user_id;

    /** 评论内容 */
    private String comment_content;

    /** 时间 */
    private Timestamp comment_date;



    public Integer getComment_id() {
        return comment_id;
    }

    public void setComment_id(Integer comment_id) {
        this.comment_id = comment_id;
    }

    public Integer getBook_id() {
        return book_id;
    }

    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getComment_content() {
        return comment_content;
    }

    public void setComment_content(String comment_content) {
        this.comment_content = comment_content;
    }

    public Timestamp getComment_date() {
        return comment_date;
    }

    public void setComment_date(Timestamp comment_date) {
        this.comment_date = comment_date;
    }
}
