package com.vp.bootstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:44
 * @Version: 1.0
 */

import lombok.Data;

/**
 * 订单详情表
 */
@Data
public class OrderDetail implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = 2877664263938829980L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** orderdetailId */
    private Integer orderdetail_id;

    /** 订单表的id */
    private Integer order_id;

    /** 书的编号 */
    private Integer book_id;

    /** 数量 */
    private Integer book_number;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getOrderdetail_id() {
        return orderdetail_id;
    }

    public void setOrderdetail_id(Integer orderdetail_id) {
        this.orderdetail_id = orderdetail_id;
    }

    public Integer getOrder_id() {
        return order_id;
    }

    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    public Integer getBook_id() {
        return book_id;
    }

    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    public Integer getBook_number() {
        return book_number;
    }

    public void setBook_number(Integer book_number) {
        this.book_number = book_number;
    }
}
